### ISSUE TITLE
Yeoman generator broken ?

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#33]
When I try to run `yo @travetto/app` I get this error

```/Users/zach.roberts/projects/brownbag/node_modules/typescript/lib/typescript.js:25137
        if (!sourceFile.statements.length) {
                                   ^

TypeError: Cannot read property 'length' of undefined
    at convertToObjectWorker (/Users/zach.roberts/projects/brownbag/node_modules/typescript/lib/typescript.js:25137:36)
    at parseOwnConfigOfJsonSourceFile (/Users/zach.roberts/projects/brownbag/node_modules/typescript/lib/typescript.js:25781:20)
    at parseConfig (/Users/zach.roberts/projects/brownbag/node_modules/typescript/lib/typescript.js:25704:13)
    at parseJsonConfigFileContentWorker (/Users/zach.roberts/projects/brownbag/node_modules/typescript/lib/typescript.js:25555:28)
    at Object.parseJsonSourceFileConfigFileContent (/Users/zach.roberts/projects/brownbag/node_modules/typescript/lib/typescript.js:25521:16)
    at Function.compileTypescript (/Users/zach.roberts/projects/brownbag/node_modules/@travetto/boot/src/register.js:91:29)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.moduleLoaderHandler (/Users/zach.roberts/projects/brownbag/node_modules/@travetto/boot/src/register.js:69:39)
    at Module.require (internal/modules/cjs/loader.js:683:19)```

this is on a freshly new laptop.  Any ideas on why?

**Comment by arciisine** [comment]
Yeah, some things got missed in the upgrades.  This is resolved in the latest rc builds for 0.7.x
