### ISSUE TITLE
1.0 upgrade fails to run rest application

### ISSUE THREAD

**Issue by ZachRoberts25** [travetto/travetto#57]
```
"dependencies": {
    "@travetto/asset-rest": "^1.0.0-beta.1",
    "@travetto/asset-s3": "^1.0.0-beta.1",
    "@travetto/auth-passport": "^1.0.0-beta.1",
    "@travetto/auth-rest": "^1.0.0-beta.1",
    "@travetto/cli": "^1.0.0-beta.1",
    "@travetto/context": "^1.0.0-beta.1",
    "@travetto/log": "^1.0.0-beta.1",
    "@travetto/model-elasticsearch": "^1.0.0-beta.1",
    "@travetto/rest-express": "^1.0.0-beta.1",
    "@travetto/rest-session": "^1.0.0-beta.1",
    "@travetto/swagger": "^1.0.0-beta.1",
    "aws-sdk": "^2.351.0",
    "moment": "^2.22.2",
    "papaparse": "^4.6.2",
    "passport-saml": "^1.0.0",
    "request": "^2.88.0",
    "request-promise": "^4.2.2",
    "ssh2-promise": "^0.1.3"
  },
```
this is my package.json

and this is my error
```error Unable to load /Users/zach.roberts/projects/engage/rest/node_modules/@travetto/di/node_modules/@travetto/registry/src/decorator.ts, most likely a cyclical dependency from node_modules/@travetto/registry/src/decorator.ts [via node_modules/@travetto/di/node_modules/@travetto/registry/src/decorator.ts] [via node_modules/@travetto/app/src/registry.ts]
    at Function.Module._load (internal/modules/cjs/loader.ts:556:12)  
    at Function.moduleLoaderHandler (node_modules/@travetto/boot/src-ts/register.ts:97:35)  
    at Module.require (internal/modules/cjs/loader.ts:683:19)  
    at require (internal/modules/cjs/helpers.ts:16:16)  
    at node_modules/@travetto/app/bin/lib/app-list.ts:29:76
```

**Comment by arciisine** [comment]
Make sure you clean.  I'm using the beta now with a similar dependency set

**Comment by ZachRoberts25** [comment]
I definitely cleaned, but I'll work more with it to see if I can figure out whats going on

**Comment by arciisine** [comment]
I assumed you had, try running with TRACE=1 and see if anything pops

**Comment by ZachRoberts25** [comment]
I noticed that "^1.0.0-beta.1" for a lot of them isn't the highest, some in npm say they max out at 0.7.x.

**Comment by arciisine** [comment]
That shouldn't be the case. Which package are you referring to?

**Comment by arciisine** [comment]
That is because I cut a 0.7.x release for some bug fixes, the 1.0.0 beta1
should still be there.  I'm using every one of your dependencies as 1.0.0
beta minus elasticsearch, as I'm using the sql model module.  I should have
some time later today if you want to do a debug session.

**Comment by arciisine** [comment]
The 1.0.0 code is in the 1.0.0-dev branch.  Let's do an interactive session
later to figure this out.
